version: '2'

services:
  proxy:
    image: traefik
    container_name: traefik_proxy
    restart: always
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$PWD/traefik.toml:/etc/traefik/traefik.toml"

networks:
  webgateway:
    external:
      name: traefik_webgateway

